### PR TITLE
Hello Microverse-1

### PR DESCRIPTION
**Pull request by audukehinde**
# In this project:
* ## I added gitignore
* ## I added GitHub flow
* ## I added Linters

### CODE REVIEW

**Review by oxenprogrammer — CHANGES_REQUESTED** [review]
Hi @audukehinde , 

Good job so far!
**To Highlight**
- [x] Descriptive README.
- [x] Gitflow correctly followed. 

I can see you're really putting effort to become a world-class software developer :+1:
There are some issues that you still need to address in order to move forward to the next project.
Trust me you got this! :muscle:


## Required Changes ♻️
- [ ] You will need to add `test.md`  file inside `.gitignore` as specified in the requirement. In case you decide to use `node_modules`, please add it as well. 

## Optional suggestions
_Consider the optional changes nice to have features and only work on them when you have satisfied the required changes_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by audukehinde** [comment]
Hello.
Thanks for your feedback. I really appreciate it.

Please, Is .gitignore a folder or a file?

Thanks.

**Comment by audukehinde** [comment]
Sorry, now I understand better. Thanks for your understanding

**Comment by audukehinde** [comment]
I have added the test.md file. Please, how do I submit?

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED ✔✔**
Hello @audukehinde 👋🏽
Your project is complete!  There is nothing else to say. It's time to merge it.
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
